# Generated by Django 4.2.1 on 2023-06-14 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mucopoly', '0002_alter_profile_mucopolysaccharidosis_muco_assent_upload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demographic_mucopolysaccharidosis',
            name='Age_at_Onset_of_symptoms_intrauterine',
            field=models.CharField(blank=True, choices=[('1', 'Yes'), ('0', 'No')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='demographic_mucopolysaccharidosis',
            name='Age_at_Presentation_intrauterine',
            field=models.CharField(blank=True, choices=[('1', 'Yes'), ('0', 'No')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='demographic_mucopolysaccharidosis',
            name='Age_at_diagnosis_intrauterine',
            field=models.CharField(blank=True, choices=[('1', 'Yes'), ('0', 'No')], max_length=5, null=True),
        ),
    ]
