# Generated by Django 4.2.1 on 2023-06-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mucopoly', '0003_alter_demographic_mucopolysaccharidosis_age_at_onset_of_symptoms_intrauterine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_mucopolysaccharidosis',
            name='muco_assent_given',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True),
        ),
    ]
