# Generated by Django 4.2.1 on 2023-06-26 11:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mucopoly', '0005_alter_profile_mucopolysaccharidosis_muco_assent_given_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_mucopolysaccharidosis',
            name='muco_assent_upload',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='profile_mucopolysaccharidosis',
            name='muco_consent_upload',
            field=models.FileField(null=True, upload_to='uploads/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
