# Generated by Django 4.1.5 on 2023-01-23 09:20

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='State',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institute_name', models.CharField(max_length=200, null=True, validators=[django.core.validators.MaxLengthValidator(200)])),
                ('address', models.CharField(blank=True, max_length=500, null=True, validators=[django.core.validators.MaxLengthValidator(500)])),
                ('email', models.EmailField(blank=True, max_length=300, null=True)),
                ('investigator_name', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.MaxLengthValidator(100)])),
                ('access', models.CharField(blank=True, choices=[('Super User', 'Super User'), ('Admin', 'Admin'), ('Nodal', 'Nodal'), ('User', 'User')], default='User', max_length=100, null=True)),
                ('disable', models.CharField(blank=True, choices=[('Activated', 'Activated'), ('Deactivated', 'Deactivated')], default='Activated', max_length=100, null=True)),
                ('deactivate_reason', models.CharField(blank=True, max_length=100, null=True)),
                ('institute_code', models.CharField(max_length=100, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='District',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.state')),
            ],
        ),
    ]
