# Generated by Django 4.0.3 on 2023-03-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='register',
            name='antenatal_screening',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='register',
            name='any_other_facility',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='register',
            name='capillary_electrophoresis',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='register',
            name='chromosomal_micro',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='register',
            name='cytogenetic',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='register',
            name='dna_sequencer',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='register',
            name='eonis_tm_system',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='register',
            name='gcms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='register',
            name='high_throughput_rna_dna',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='register',
            name='hplc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='register',
            name='liquid_chromatography',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='register',
            name='mi_seq',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='register',
            name='microfluidics_platform',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='register',
            name='multimode_reader',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='register',
            name='newborn_screening',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='register',
            name='next_seq',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='register',
            name='quality_check',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='register',
            name='real_time_pcr',
            field=models.BooleanField(default=False),
        ),
    ]
