# Generated by Django 4.0.3 on 2023-05-08 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_register_antenatal_screening_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Opd_attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('name_of_rd', models.CharField(blank=True, max_length=100, null=True)),
                ('no_of_cases', models.CharField(blank=True, max_length=100, null=True)),
                ('no_of_opd_cases', models.CharField(blank=True, max_length=100, null=True)),
                ('no_of_new_adminission', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
