# Generated by Django 4.0.3 on 2023-05-12 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_opd_attendance_user_alter_opd_attendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opd_attendance',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
