# Generated by Django 4.0.3 on 2023-05-12 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_alter_opd_attendance_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opd_attendance',
            name='name_of_rd',
        ),
        migrations.AddField(
            model_name='opd_attendance',
            name='name_of_rdei',
            field=models.CharField(blank=True, choices=[('Illiterate', 'Illiterate'), ('Primary', 'Primary'), ('High School', 'High School'), ('Secondary level', 'Secondary level'), ('College and above', 'College and above')], max_length=50, null=True),
        ),
    ]
