# Generated by Django 4.0.3 on 2023-05-19 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_opd_attendance_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opd_attendance',
            name='no_of_cases',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='opd_attendance',
            name='no_of_new_adminission',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='opd_attendance',
            name='no_of_opd_cases',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='opd_attendance',
            name='pre_new_admi',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='opd_attendance',
            name='pre_opd_att',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
