# Generated by Django 4.0.3 on 2023-05-26 10:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_alter_opd_attendance_no_of_cases_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opd_attendance',
            name='date',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
