# Generated by Django 4.0.3 on 2023-05-31 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_alter_opd_attendance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='opd_attendance',
            name='pre_total',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
