# Generated by Django 4.2.1 on 2023-06-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_opd_attendance_pre_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opd_attendance',
            name='date',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='opd_attendance',
            name='name_of_rdei',
            field=models.CharField(choices=[('Fabry Disease', 'Fabry Disease'), ('Thalassemia', 'Thalassemia'), ('Glycogen Storage Disorder', 'Glycogen Storage Disorder'), ('Bleeding Disorder', 'Bleeding Disorder'), ('IEM', 'IEM'), ('Pompe Disease', 'Pompe Disease'), ('Sphingo Lipidosis', 'Sphingo Lipidosis'), ('Skeletal Dysplasia', 'Skeletal Dysplasia'), ('NMD', 'NMD'), ('Mucopolysaccharidosis Group', 'Mucopolysaccharidosis Group'), ('Small molecule samples', 'Small molecule samples'), ('PID', 'PID')], max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='opd_attendance',
            name='no_of_cases',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='opd_attendance',
            name='no_of_new_adminission',
            field=models.PositiveBigIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='opd_attendance',
            name='no_of_opd_cases',
            field=models.PositiveBigIntegerField(null=True),
        ),
    ]
