# Generated by Django 4.2.1 on 2023-06-14 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabry', '0002_alter_profile_fabry_fb_assent_given_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demographic_fabry',
            name='fb_presenting_complaints_age_diagnosis_intrauterine',
            field=models.CharField(blank=True, choices=[('1', 'Yes'), ('0', 'No')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='demographic_fabry',
            name='fb_presenting_complaints_age_presentation_intrauterine',
            field=models.CharField(blank=True, choices=[('1', 'Yes'), ('0', 'No')], max_length=5, null=True),
        ),
        migrations.AlterField(
            model_name='demographic_fabry',
            name='fb_presenting_complaints_intrauterine',
            field=models.CharField(blank=True, choices=[('1', 'Yes'), ('0', 'No')], max_length=5, null=True),
        ),
    ]
