# Generated by Django 4.2.1 on 2023-07-12 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabry', '0006_alter_profile_fabry_fb_assent_upload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_fabry',
            name='complete',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Na', 'Na')], default=False, max_length=10, null=True),
        ),
    ]
