# Generated by Django 4.2.1 on 2023-07-12 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fabry', '0008_alter_profile_fabry_complete'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_fabry',
            name='complete',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Na', 'Na')], default='No', max_length=10, null=True),
        ),
    ]
