# Generated by Django 4.2.1 on 2023-06-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bleeding', '0002_alter_profile_bleeding_bd_assent_given_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_bleeding',
            name='bd_assent_given',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True),
        ),
    ]
