# Generated by Django 4.2.1 on 2023-06-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thalasemia', '0002_alter_profile_thalassemia_th_assent_upload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_thalassemia',
            name='th_assent_given',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No'), ('Unable to assent', 'Unable to assent')], max_length=30, null=True),
        ),
    ]
