# Generated by Django 4.2.1 on 2023-06-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thalasemia', '0003_alter_profile_thalassemia_th_assent_given'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_thalassemia',
            name='th_assent_given',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No'), ('Unable to assent', 'Unable to assent')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='profile_thalassemia',
            name='th_assent_upload',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
