# Generated by Django 4.2.1 on 2023-06-12 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pid', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_pid',
            name='pid_assent_given',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile_pid',
            name='pid_assent_upload',
            field=models.FileField(null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='profile_pid',
            name='pid_consent_upload',
            field=models.FileField(null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='profile_pid',
            name='pid_date_of_birth',
            field=models.DateField(null=True),
        ),
    ]
