# Generated by Django 4.2.1 on 2023-06-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pid', '0003_alter_profile_pid_pid_assent_given'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demopraphic_pid',
            name='pid_date_onset_symptoms',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profile_pid',
            name='pid_assent_given',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile_pid',
            name='pid_assent_upload',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
