# Generated by Django 4.2.1 on 2023-06-26 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pid', '0004_alter_demopraphic_pid_pid_date_onset_symptoms_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demopraphic_pid',
            name='pid_date_onset_symptoms',
            field=models.CharField(blank=True, choices=[('Known ', 'Known '), ('Unknown', 'Unknown')], max_length=100, null=True),
        ),
    ]
