# Generated by Django 4.2.1 on 2023-06-26 11:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pid', '0005_alter_demopraphic_pid_pid_date_onset_symptoms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_pid',
            name='pid_assent_upload',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
        migrations.AlterField(
            model_name='profile_pid',
            name='pid_consent_upload',
            field=models.FileField(null=True, upload_to='uploads/%Y/%m/%d/', validators=[django.core.validators.FileExtensionValidator(['pdf'])]),
        ),
    ]
