# Generated by Django 4.2.1 on 2023-06-14 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skeletal', '0002_alter_profile_skeletal_sk_assent_upload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demographic_skeletal',
            name='sk_Age_at_diagnosis_Intrauterine',
            field=models.CharField(blank=True, choices=[('1', 'Yes'), ('0', 'No')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='demographic_skeletal',
            name='sk_Age_at_onset_of_symptoms_Intrauterine',
            field=models.CharField(blank=True, choices=[('1', 'Yes'), ('0', 'No')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='demographic_skeletal',
            name='sk_Age_at_presentation_Intrauterine',
            field=models.CharField(blank=True, choices=[('1', 'Yes'), ('0', 'No')], max_length=20, null=True),
        ),
    ]
