# Generated by Django 4.2.1 on 2023-06-14 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iem', '0002_alter_profile_metabolism_mt_assent_upload_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demographic_matabolism',
            name='mt_presenting_complaints_age_diagnosis_intrauterine',
            field=models.CharField(blank=True, choices=[('1', 'Yes'), ('0', 'No')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='demographic_matabolism',
            name='mt_presenting_complaints_age_presentation_intrauterine',
            field=models.CharField(blank=True, choices=[('1', 'Yes'), ('0', 'No')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='demographic_matabolism',
            name='mt_presenting_complaints_intrauterine',
            field=models.CharField(blank=True, choices=[('1', 'Yes'), ('0', 'No')], max_length=10, null=True),
        ),
    ]
