# Generated by Django 4.2.1 on 2023-06-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iem', '0003_alter_demographic_matabolism_mt_presenting_complaints_age_diagnosis_intrauterine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_metabolism',
            name='mt_assent_given',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True),
        ),
    ]
