# Generated by Django 4.2.1 on 2023-06-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glycogen', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_glycogen',
            name='gl_assent_given',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True),
        ),
    ]
