# Generated by Django 4.2.1 on 2023-06-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('glycogen', '0002_alter_profile_glycogen_gl_assent_given'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_glycogen',
            name='gl_assent_given',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile_glycogen',
            name='gl_assent_upload',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
