# Generated by Django 4.2.1 on 2023-06-26 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pompe', '0003_alter_demographic_pompe_pd_age_at_diagnosis_intrauterine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demographic_pompe',
            name='pd_Age_at_diagnosis_Intrauterine',
            field=models.CharField(blank=True, choices=[('1', 'Yes'), ('0', 'No')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='demographic_pompe',
            name='pd_Age_at_onset_of_symptoms_Intrauterine',
            field=models.CharField(blank=True, choices=[('1', 'Yes'), ('0', 'No')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='demographic_pompe',
            name='pd_Age_at_presentation_Intrauterine',
            field=models.CharField(blank=True, choices=[('1', 'Yes'), ('0', 'No')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='profile_pompe',
            name='pmp_assent_given',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True),
        ),
    ]
