# Generated by Django 4.2.1 on 2023-06-26 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pompe', '0004_alter_demographic_pompe_pd_age_at_diagnosis_intrauterine_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile_pompe',
            name='pmp_assent_given',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='profile_pompe',
            name='pmp_assent_upload',
            field=models.FileField(blank=True, null=True, upload_to='uploads/%Y/%m/%d/'),
        ),
    ]
