# Generated by Django 4.2.1 on 2023-07-03 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pompe', '0006_alter_profile_pompe_pmp_assent_upload_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='demographic_pompe',
            name='pd_name_of_com',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], max_length=30, null=True),
        ),
    ]
